# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: myvariable
  value: myvalue
- group: TestVariableGroup

steps:
- script: 'echo Hello, world! Bert token: $(BERT_TOKEN)'
  displayName: 'Variable Group Test.'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- ${{ if eq(variables.CODACY_PROJECT_TOKEN, True) }}:
  - script: 'echo Hello, we have a codacy project token defined!'
- ${{ else }}:
  - script: 'echo No codacy project token defined sadface. CODACY_PROJECT_TOKEN: $(CODACY_PROJECT_TOKEN)'

- ${{ if containsValue(variables.*.key, 'CODACY_PROJECT_TOKEN') }}:
  - script: 'echo We got codacy in variables'
    displayName: Variables contains codacy key