name: 1.0.0$(Rev:.r)
trigger:
- main
- feature/*

pool:
  vmImage: 'windows-2019'

resources:
  repositories:
  - repository: templates
    name: Fredproj/FredShared

jobs:
- template: CodacyCodeCoverage.yml@templates
  parameters:
    CodacyProjectPath: badbort/Fredproj
    CodacyProjectName: Fredproj
    CodacyOrganizationProvider: gh