name: Migration from Azure DevOps

on:
  workflow_dispatch:
    inputs:
      source-repository:
        description: Git url for the repo being migrated. e.g. https://racwa@dev.azure.com/racwa/MRP/_git/VehiclesApi
    
jobs:
  clone-and-merge: # This job is run manually
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' # We only want this job running from manual actions
    steps:
      - run: |
          echo "TARGET_GIT_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" >> $GITHUB_ENV
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: target
          
      - name: Check branch does not exist
        working-directory: target
        run: |
          exists=`git show-ref refs/heads/main` || echo;
          
          if [ -n "$exists" ]; then
              echo "::error::Migration branch already exists. Please delete this branch and run the workflow again"
              exit 1
          else
              echo 'migration branch does not exist'
          fi
          
      - run:  git clone --mirror ${{ inputs.source-repository }} source
      
      - run: |
          git lfs fetch --all
          git fetch --all --tags
        working-directory: source
        
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
          git remote add source ../source --fetch --tags
          git checkout -b feature/migration
          git merge source/main --allow-unrelated-histories -X theirs
          git lfs fetch source --all
          git log
        working-directory: target
