name: Migration from Azure DevOps

on:
  workflow_dispatch:
    inputs:
      source-repository:
        description: Git url for the repo being migrated. e.g. https://racwa@dev.azure.com/racwa/MRP/_git/VehiclesApi
        required: true
      dry-run:
        description: Enables try run which will disable pushes
        required: true
        type: boolean
    
jobs:
  clone-and-merge: # This job is run manually
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' # We only want this job running from manual actions
    steps:
      - run: |
          echo "TARGET_GIT_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" >> $GITHUB_ENV
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: target
          
      - name: Check branch does not exist
        working-directory: target
        run: |
          exists=`git show-ref refs/heads/migration` || echo;
          
          echo $exists
          
          if [ `git branch | egrep "^[[:space:]]+migration$"` ]
          then
              echo "::error::Migration branch already exists. Please delete this branch and run the workflow again"
              exit 1
          else
              echo 'migration branch does not exist'
          fi
          
      - run:  git clone --mirror ${{ inputs.source-repository }} source
      
      - run: |
          git lfs fetch --all
          git fetch --all --tags
        working-directory: source
        
      - name: Merge source into target
        working-directory: target
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
          git remote add source ../source --fetch --tags
          git checkout -b migration
          git merge source/main --allow-unrelated-histories -X theirs
          git lfs fetch source --all
                    
          git remote remove source
        
      - name: Print Diagram
        working-directory: target
        run: |
          git log --all --decorate --oneline --graph --date=short --pretty="%ad - %s" > $GITHUB_STEP_SUMMARY
    
      - name: Push Migration Changes
        working-directory: target
        if: ${{ !inputs.dry-run }}
        run: |
          git push --set-upstream origin migration
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'DevOps Migration from ${{inputs.source-repository}}'
          path: target
