name: Migration from Azure DevOps

on:
  workflow_dispatch:
    inputs:
      azure-project:
        description: Azure project name. e.g. enter MRP for https://racwa@dev.azure.com/racwa/MRP/_git/VehiclesApi
        required: true
      azure-repo:
        description: Name of the repo, e.g. enter VehiclesApi for https://racwa@dev.azure.com/racwa/MRP/_git/VehiclesApi
        required: true
      dry-run:
        description: Enables dry run which will disable any pushes and make no changes
        required: true
        type: boolean
    
jobs:
  clone-and-merge: # This job is run manually
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "TARGET_GIT_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" >> $GITHUB_ENV
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: target
          
      - name: Check branch does not exist
        working-directory: target
        shell: bash
        run: |
          migrationExists=$(git ls-remote --heads origin migration)
          
          if [[ -z "$migrationExists" ]]; then
              echo 'Migration branch does not exist. Continuing'
          else
              echo "::error::Migration branch already exists. Please delete this branch and run the workflow again"
              exit 1
          fi
          
      - shell: bash
        run: |
      
          echo "Cloning repo..."
          git clone --mirror https://bertington@dev.azure.com/bertington/${{ inputs.azure-project }}/_git/${{ inputs.azure-repo }} source
          
          cd source
        
      - name: Merge source into target
        working-directory: target
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
          git remote add source ../source --fetch --tags
          git checkout -b migration
          git merge source/main --allow-unrelated-histories -X theirs
                    
          git remote remove source
        
      - name: Print Diagram
        working-directory: target
        run: |
          echo "### Git Log:" >> $GITHUB_STEP_SUMMARY
          git log --all --decorate --oneline --graph --date=short --pretty="%ad - %s" >> $GITHUB_STEP_SUMMARY
    
      - name: Push Migration Changes
        working-directory: target
        if: ${{ !inputs.dry-run }}
        run: |
          git push --follow-tags --set-upstream origin migration
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'DevOps Migration from ${{inputs.azure-project}}/${{inputs.azure-repo}}'
          path: target
